### ISSUE TITLE
安装后并没有效果。

### ISSUE THREAD

**Issue by skywalkerwhack** [Zgrowth/HiFiScript#2]
首先我在浏览器中下载了 Tampermonkey 插件，之后安装此 脚本后转到 hifini.com 但是并为出现任何 Readme 中所示的图标。
此时点击 Tampermonkey 发现 没有脚本正在运行。 但是 dashboard 里面是显示 enabled 了， 打开editor 进行Syntax check 提示 8 个错误。

**Comment by Dlian-Zero** [comment]
> 首先我在浏览器中下载了 Tampermonkey 插件，之后安装此 脚本后转到 hifini.com 但是并为出现任何 Readme 中所示的图标。 此时点击 Tampermonkey 发现 没有脚本正在运行。 但是 dashboard 里面是显示 enabled 了， 打开editor 进行Syntax check 提示 8 个错误。

// @match        https://www.hifini.com/*  改成// @match        https://hifini.com/*就行了

**Comment by ghost** [comment]
> > 首先我在浏览器中下载了 Tampermonkey 插件，之后安装此 脚本后转到 hifini.com 但是并为出现任何 Readme 中所示的图标。 此时点击 Tampermonkey 发现 没有脚本正在运行。 但是 dashboard 里面是显示 enabled 了， 打开editor 进行Syntax check 提示 8 个错误。
> 
> // @match https://www.hifini.com/* 改成// @match [https://hifini.com/*就行了](https://hifini.com/*%E5%B0%B1%E8%A1%8C%E4%BA%86)

非常感谢您，问题解决了。

**Comment by Dlian-Zero** [comment]
> > > 首先我在浏览器中下载了 Tampermonkey 插件，之后安装此 脚本后转到 hifini.com 但是并为出现任何 Readme 中所示的图标。此时点击 Tampermonkey 发现 没有脚本正在运行。但是 dashboard 里面是显示 enabled 了， 打开editor 进行Syntax check 提示 8 个错误。
> > 
> > 
> > //  https://www.hifini.com/* 改成 //  [https://hifini.com/*就行了](https://hifini.com/*%E5%B0%B1%E8%A1%8C%E4%BA%86)
> 
> 非常感谢您，问题解决了。

网站关闭了  T A T
